#!/usr/bin/env python3
"""
Build script for tutorials/03-glass-ir.ipynb.

This lesson is a hybrid — the user runs Gallowglass cells in the
Jupyter kernel, but the rendered Glass IR appears as static text in
markdown cells. The IR is regenerated each time the build script
runs, so committed pin hashes always match the current emit
discipline.
"""

from __future__ import annotations

import os
import sys
from typing import Any

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

import nbformat
from nbformat import v4

from bootstrap.lexer import lex
from bootstrap.parser import parse
from bootstrap.scope import resolve
from bootstrap.codegen import Compiler
from bootstrap.glass_ir import render_fragment
from bootstrap.pin import compute_pin_id
from bootstrap.mcp_server import _typecheck_capture, load_prelude
from bootstrap.jupyter_kernel import GallowglassEvaluator

from dev.harness.plan import P


# Lazy: build once, reuse for every render call below.
_PRELUDE = None


def _prelude():
    global _PRELUDE
    if _PRELUDE is None:
        _PRELUDE = load_prelude()
    return _PRELUDE


def render_ir_fragment(src: str, name: str, module: str = 'Demo') -> str:
    """Compile ``src`` against the prelude and return the Glass IR
    fragment for ``name``. The fragment includes the pin hash, source
    Loc, and pretty-printed body — exactly what gets shown to a
    consumer of the typed IR layer."""
    prelude = _prelude()
    prog = parse(lex(src, '<demo>'), '<demo>')
    resolved, env = resolve(prog, module, prelude.module_envs, '<demo>')
    te, _, _ = _typecheck_capture(
        resolved, env, module, '<demo>',
        prior_te=prelude.type_env,
        prior_tc=prelude.type_constructors,
    )
    compiler = Compiler(
        module=module, pre_compiled=prelude.compiled,
        pre_class_methods=prelude.class_methods,
        pre_class_defaults=prelude.class_defaults,
        pre_class_constraints=prelude.class_constraints,
        pre_con_info=prelude.con_info,
    )
    compiled = compiler.compile(resolved)
    val = P(compiled[f'{module}.{name}'])
    pin_id = compute_pin_id(val)
    for d in resolved.decls:
        if hasattr(d, 'name') and d.name == name:
            return render_fragment(
                f'{module}.{name}', d,
                pin_id=pin_id, module=module, type_env=te,
            ).rstrip()
    raise RuntimeError(f'declaration {name!r} not found')


def md_with_ir(intro: str, src: str, name: str) -> str:
    """A markdown cell that shows the source plus its rendered Glass
    IR in a code block. The IR is regenerated by this script, so it
    always reflects the current emit behaviour."""
    ir = render_ir_fragment(src, name)
    return (f'{intro}\n\n'
            f'```\n{ir}\n```')


# Source snippets that we both run as code cells and render to IR
# in markdown — keeping them in sync between the two presentations.
TWICE_SRC = 'let twice : Nat → Nat = λ n → n + n'
FACTORIAL_SRC = ('let factorial : Nat → Nat\n'
                 '  = fix λ self n → match n {\n'
                 '      | 0 → 1\n'
                 '      | _ → n * self n\n'
                 '    }')


def cells() -> list[tuple[str, str]]:
    """The cell list. Built dynamically so the IR renderings get
    refreshed each time the script runs."""
    return [
        ('md', '''# Glass IR — what the compiler actually emits

Gallowglass compiles to PLAN, but in between source and PLAN there's \
a typed intermediate representation called **Glass IR**. It carries \
the source `Loc`, the inferred type, the effect row, contract \
clauses, and a BLAKE3-256 pin hash that content-addresses the \
binding. It's the layer an editor / language server / MCP consumer \
of compiler output reads.

This notebook shows what Glass IR looks like for a few example \
declarations. The IR appears as static text in markdown cells — \
generated by a build script that runs the bootstrap pipeline and \
asks `bootstrap.glass_ir.render_fragment` for each fragment, so \
the pin hashes you see were computed against the current state of \
the compiler.'''),

        ('md', md_with_ir(
            '## A simple function\n\n'
            'The Gallowglass source:\n\n'
            f'```gallowglass\n{TWICE_SRC}\n```\n\n'
            'compiles to this IR fragment:',
            TWICE_SRC, 'twice',
        )),

        ('md',
         'Reading top-down:\n\n'
         '* `pin#…` — first eight hex chars of the BLAKE3-256 of the '
         'compiled value. Two different bindings with structurally '
         'identical bodies share the same pin.\n'
         '* `<demo>:1:1` — source location. Stays attached through '
         'the pipeline so error messages and tooling can map back.\n'
         '* `Demo.twice [pin#…] : Nat → Nat` — fully-qualified name, '
         'pin reference, inferred type.\n'
         '* `= λ n → n + n` — the body in canonical Gallowglass '
         'syntax. Round-trips: parsing this back produces the same '
         'PLAN value.'),

        ('md', '## A recursive function with pattern matching\n\n'
               'The same shape, but with `fix` for self-recursion '
               'and a `match` body:'),

        ('md', md_with_ir(
            'Source:\n\n'
            f'```gallowglass\n{FACTORIAL_SRC}\n```\n\nIR:',
            FACTORIAL_SRC, 'factorial',
        )),

        ('md',
         'Two things to notice. First: the body in the IR is *not* '
         'a flat textual copy of the source — it\'s the result of '
         'running parse → scope → typecheck → render. So `self` is '
         'recovered from the `fix` introduction even though the '
         'compiled PLAN value uses a de Bruijn index for it.\n\n'
         'Second: the pin hash captures the whole shape. Change '
         'the body in any way that affects the compiled PLAN value '
         '— add a guard, rename a binder, replace `*` with `+` — '
         'and the pin hash changes. Identical bodies in different '
         'modules get the same pin and dedupe in the emit layer.'),

        ('md', '## Pin hashes and content addressing\n\n'
               'Pins are how cross-module deduplication works. When '
               'two modules contain bindings whose compiled values '
               'are bit-identical, the emit layer notices via pin '
               'equality and emits one Plan Asm `(#bind …)` for '
               'both. PR #81 in the project history was the dedup '
               'discipline that took the Compiler.gls emit from '
               '~1.7 GB to ~775 KB.'),

        ('md', '## Where you actually see Glass IR\n\n'
               'In day-to-day Gallowglass use you don\'t look at IR '
               'directly — the compiler does. But the layer is '
               'visible through:\n\n'
               '* The MCP server (`python3 -m bootstrap.mcp_server`) '
               '— exposes `compile_snippet`, `infer_type`, and '
               '`render_fragment` over stdio for LLM consumers.\n'
               '* The Jupyter kernel itself uses the typecheck '
               'output to drive the constructor-name renderer in '
               'cell output (the same mechanism that gives you '
               '`MkPair 3 7` instead of `((0 3) 7)`).\n\n'
               'For the full IR grammar see `spec/01-glass-ir.md`.'),

        ('md', '## Verifying it lives — running a cell against the kernel\n\n'
               'The IR you see above was generated against this same '
               'compile pipeline; the cell below evaluates the same '
               'function definition in the live kernel and calls '
               'it. The kernel\'s output uses the type-driven '
               'renderer, which itself reads the typecheck `con_info` '
               'and `type_env` that drives Glass IR rendering.'),

        ('code', TWICE_SRC),
        ('code', 'twice 21'),

        ('md', '## What\'s next\n\n'
               'The final lesson, `04-effects-and-handlers.ipynb`, '
               'covers Gallowglass\'s effect system — how effects '
               'appear in type signatures, the `eff` declaration, '
               'and the `handle` form. Running effectful '
               'computations from cells has a wrinkle the kernel '
               'doesn\'t fully expose yet, but the syntax itself '
               'is the part that matters for understanding the '
               'language.'),
    ]


def _render_outputs(text: str | None, html: str | None,
                    execution_count: int) -> list[Any]:
    if text is None and html is None:
        return []
    data: dict[str, Any] = {}
    if text is not None:
        data['text/plain'] = text
    if html is not None:
        data['text/html'] = html
    return [v4.new_output('execute_result', data=data,
                          execution_count=execution_count, metadata={})]


def main() -> None:
    nb = v4.new_notebook()
    nb.metadata['kernelspec'] = {
        'name': 'gallowglass',
        'display_name': 'Gallowglass',
        'language': 'gallowglass',
    }
    nb.metadata['language_info'] = {
        'name': 'gallowglass',
        'mimetype': 'text/x-gallowglass',
        'file_extension': '.gls',
        'pygments_lexer': 'haskell',
    }

    evaluator = GallowglassEvaluator()
    exec_count = 0

    for kind, body in cells():
        if kind == 'md':
            nb.cells.append(v4.new_markdown_cell(body, id=f"md-{len(nb.cells):02d}"))
            continue
        exec_count += 1
        result = evaluator.eval_cell(body)
        if result.error is not None:
            print(f'WARN: cell {exec_count} errored: {result.error}',
                  file=sys.stderr)
        outputs = _render_outputs(result.value_text, result.value_html,
                                  execution_count=exec_count)
        cell = v4.new_code_cell(source=body, outputs=outputs, id=f"code-{exec_count:02d}")
        cell['execution_count'] = exec_count
        nb.cells.append(cell)

    out_path = os.path.join(os.path.dirname(__file__),
                            '03-glass-ir.ipynb')
    with open(out_path, 'w') as f:
        nbformat.write(nb, f)
    print(f'wrote {out_path}')


if __name__ == '__main__':
    main()
